### ISSUE TITLE
Use System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by panesofglass** [panesofglass/FSharp.Data.JsonSchema#4]
As we are essentially overriding nearly everything in Newtonsoft.Json's default serialization settings for F# types, moving to System.Text.Json is mostly a re-implementation to use its converters. This depends on NJsonSchema support for System.Text.Json, which is currently a [WIP](https://github.com/RicoSuter/NJsonSchema/issues/1014).

Steps:
- [x] [NJsonSchema Support](https://github.com/RicoSuter/NJsonSchema/issues/1014)
- [x] Update type converters to use System.Text.Json converters
- [x] Add System.Text.Json converters for F# records and anonymous records

Notes:
[Migration Guide](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)

**Comment by panesofglass** [comment]
Should this replace the Newtonsoft.Json implementation, or should this be another option and another package?

**Comment by panesofglass** [comment]
I'd say go ahead and make the switch. Things are trending towards STJ, and the excellent library that @Tarmil provides covers enough of the gaps that I was concerned with.

_Originally posted by @baronfel in https://github.com/panesofglass/FSharp.Data.JsonSchema/pull/5#issuecomment-638851419_

**Comment by isaacabraham** [comment]
This seems good - one less dependency in the chain as well as the perf gains.

**Comment by panesofglass** [comment]
With no more comments, I'll go ahead and merge. I can always resurrect this later, if there's a need.
