### ISSUE TITLE
DOCUMENTATION.md or Just the README?

### ISSUE THREAD

**Issue by panesofglass** [panesofglass/FSharp.Data.JsonSchema#6]
I was going to start adding more documentation as I try to get this to a 1.0 release. Should I follow @dustinmoris approach of using a [`DOCUMENTATION.md`](https://dusted.codes/open-source-documentation) or just put it all in the `README`?

**Comment by matthewcrews** [comment]
In my opinion, a `README` is sufficient especially if there is a Table of Contents with links.
